steps:
  # 1. Build and Test
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-f', 'task-service/pom.xml']
    id: 'build-test'

  # 2. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/infra-earth-367100/kube-repo/task-service:$SHORT_SHA \
                     -t us-central1-docker.pkg.dev/infra-earth-367100/kube-repo/task-service:latest \
                     -f task-service/Dockerfile \
                     task-service
    id: 'docker-build'
    waitFor: ['build-test']

  # 3. Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/infra-earth-367100/kube-repo/task-service:$SHORT_SHA']
    id: 'docker-push-sha'
    waitFor: ['docker-build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/infra-earth-367100/kube-repo/task-service:latest']
    id: 'docker-push-latest'
    waitFor: ['docker-build']

  # 4. Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials kube-cloud-cluster --zone us-central1-a --project infra-earth-367100

        if [[ "$BRANCH_NAME" == "main" ]]; then
          NAMESPACE="prod"
        elif [[ "$BRANCH_NAME" == feature/sprint-07* ]]; then
          NAMESPACE="dev-sprint7"
        elif [[ "$BRANCH_NAME" == "dev" ]]; then
          NAMESPACE="dev"
        else
          echo "Feature branch. Skipping deploy."
          exit 0
        fi

        # Replace placeholders in deployment.yaml
        sed "s/TAG_NAME/$SHORT_SHA/g" k8s/task-service/deployment.yaml > k8s/task-service/deployment.yaml.tmp
        sed -i "s/GOOGLE_CLOUD_PROJECT/infra-earth-367100/g" k8s/task-service/deployment.yaml.tmp

        # Apply
        kubectl apply -f k8s/task-service/deployment.yaml.tmp -n $$NAMESPACE
        kubectl apply -f k8s/task-service/service.yaml -n $$NAMESPACE
    id: 'deploy-gke'
    waitFor: ['docker-push-sha', 'docker-push-latest']

options:
  logging: CLOUD_LOGGING_ONLY
